package main

import "testing"

// TestUint16ToProquintKnownVectors pins the proquint encoding to the
// canonical values from Wilkerson 2009 sec. 3, "Encoding Examples". These
// are the load-bearing vectors that lock the consonant/vowel ordering and
// bit-shift layout. If anyone ever changes the alphabets or bit packing,
// these tests will catch it.
func TestUint16ToProquintKnownVectors(t *testing.T) {
	cases := []struct {
		in   uint16
		want string
	}{
		// From the Wilkerson paper, table of IP-address example encodings.
		// IP 127.0.0.1 = 0x7F000001, which encodes as "lusab-babad".
		{0x7F00, "lusab"},
		{0x0001, "babad"},

		// IP 63.84.220.193 = 0x3F54DCC1 -> "gutih-tugad".
		{0x3F54, "gutih"},
		{0xDCC1, "tugad"},

		// Edge values prove both alphabets' first and last entries.
		{0x0000, "babab"},
		{0xFFFF, "zuzuz"},
	}
	for _, c := range cases {
		got := uint16ToProquint(c.in)
		if got != c.want {
			t.Errorf("uint16ToProquint(0x%04x) = %q, want %q", c.in, got, c.want)
		}
	}
}

// TestProquintLengths verifies the structural invariants: a proquint-1 is
// always exactly 5 characters and a proquint-2 is always exactly 11 (5 + '-'
// + 5). These are filename-shape contracts.
func TestProquintLengths(t *testing.T) {
	b := []byte{0x12, 0x34, 0x56, 0x78}
	if got := proquint1FromBytes(b); len(got) != 5 {
		t.Fatalf("proquint1FromBytes len = %d, want 5 (%q)", len(got), got)
	}
	if got := proquint2FromBytes(b); len(got) != 11 {
		t.Fatalf("proquint2FromBytes len = %d, want 11 (%q)", len(got), got)
	}
}

// TestProquintAlphabetMembership sweeps the full 16-bit space to prove every
// generated byte sits in the expected consonant or vowel alphabet position.
func TestProquintAlphabetMembership(t *testing.T) {
	contains := func(s string, c byte) bool {
		for i := 0; i < len(s); i++ {
			if s[i] == c {
				return true
			}
		}
		return false
	}
	for n := 0; n < 65536; n++ {
		q := uint16ToProquint(uint16(n))
		if len(q) != 5 {
			t.Fatalf("n=%d: length=%d", n, len(q))
		}
		positions := []struct {
			pos      int
			alphabet string
			kind     string
		}{
			{0, proquintCons, "consonant"},
			{1, proquintVows, "vowel"},
			{2, proquintCons, "consonant"},
			{3, proquintVows, "vowel"},
			{4, proquintCons, "consonant"},
		}
		for _, position := range positions {
			if !contains(position.alphabet, q[position.pos]) {
				t.Fatalf("n=%d q=%q: position %d byte %q not in %s alphabet",
					n, q, position.pos, q[position.pos], position.kind)
			}
		}
	}
}

// TestProquintFullSpaceUniqueness proves the 65,536 uint16 values produce
// 65,536 distinct proquints, so collision checks are not false positives.
func TestProquintFullSpaceUniqueness(t *testing.T) {
	seen := make(map[string]uint16, 65536)
	for n := 0; n < 65536; n++ {
		q := uint16ToProquint(uint16(n))
		if previous, duplicate := seen[q]; duplicate {
			t.Fatalf("collision: %q from n=%d and n=%d", q, previous, n)
		}
		seen[q] = uint16(n)
	}
	if len(seen) != 65536 {
		t.Fatalf("seen size = %d, want 65536", len(seen))
	}
}
