#!/usr/bin/env bash

# GENERATED BY decomk stage-0 templates. DO NOT EDIT DIRECTLY.
# Customize container behavior through shared decomk.conf and Makefile content.

set -euo pipefail

die() {
  echo "decomk bootstrap: $*" >&2
  exit 1
}

# Intent: Expose explicit lifecycle phases through one stage-0 script so
# devcontainer hooks can call the same bootstrap logic with clear phase inputs.
# Source: DI-001-20260416-223600 (TODO/001)
stage0_phase="postCreate"
if [[ $# -gt 0 ]]; then
  stage0_phase="$1"
  shift
fi
if [[ $# -gt 0 ]]; then
  die "unexpected positional args: $* (expected only updateContent or postCreate)"
fi
case "$stage0_phase" in
  updateContent|postCreate)
    ;;
  *)
    die "invalid stage-0 phase: $stage0_phase (expected updateContent or postCreate)"
    ;;
esac

# Intent: Fail loudly when the runtime OS is not Ubuntu. GitHub Codespaces
# silently drops into a default fallback container (Alpine-based) when a
# devcontainer's Docker build fails. The Codespace comes up, the shell works,
# and decomk's apt-pinned workflow quietly runs against the wrong base.
# Catch the fallback here, before any pins are consumed.
# Source: (proposed; see issue filed against stevegt/decomk by JJ 2026-04-19)
if [[ ! -r /etc/os-release ]]; then
  die "cannot read /etc/os-release; decomk stage-0 requires Ubuntu but the OS cannot be identified. This usually means the devcontainer build failed and the platform dropped into a non-Ubuntu fallback image."
fi
# shellcheck source=/dev/null
. /etc/os-release
if [[ "${ID:-}" != "ubuntu" ]]; then
  die "decomk stage-0 requires Ubuntu (ID=ubuntu in /etc/os-release); got ID='${ID:-<unset>}' NAME='${NAME:-<unset>}'. This usually means the devcontainer's Docker build failed and the platform (e.g. GitHub Codespaces) dropped into its default fallback image. Fix the devcontainer build; do not treat this as a transient error."
fi

# Intent: Implement generic stage-0 bootstrap with URI-based source expressions
# so tool/config acquisition is explicit, deterministic, and shared between
# generated examples and `decomk init` scaffolds.
# Source: DI-001-20260412-170500 (TODO/001)
DECOMK_HOME="${DECOMK_HOME:-/var/decomk}"
DECOMK_LOG_DIR="${DECOMK_LOG_DIR:-/var/log/decomk}"
DECOMK_TOOL_URI="${DECOMK_TOOL_URI:-go:github.com/stevegt/decomk/cmd/decomk@stable}"
DECOMK_CONF_URI="${DECOMK_CONF_URI:-}"
DECOMK_RUN_ARGS="${DECOMK_RUN_ARGS:-all}"
DECOMK_UPDATE_CONTENT_RUN_ARGS="${DECOMK_UPDATE_CONTENT_RUN_ARGS:-$DECOMK_RUN_ARGS}"
DECOMK_POST_CREATE_RUN_ARGS="${DECOMK_POST_CREATE_RUN_ARGS:-$DECOMK_RUN_ARGS}"
DECOMK_STAGE0_PHASE="$stage0_phase"

export DECOMK_HOME DECOMK_LOG_DIR DECOMK_TOOL_URI DECOMK_CONF_URI
export DECOMK_RUN_ARGS DECOMK_UPDATE_CONTENT_RUN_ARGS DECOMK_POST_CREATE_RUN_ARGS DECOMK_STAGE0_PHASE

require_clean_git_repo() {
  local repo_dir="$1"
  if [[ -n "$(git -C "$repo_dir" status --porcelain --untracked-files=normal)" ]]; then
    die "git repo has uncommitted changes: $repo_dir"
  fi
}

parse_git_uri() {
  local uri="$1"
  if [[ "$uri" != git:* ]]; then
    die "git source URI must start with git: (got: $uri)"
  fi

  local payload="${uri#git:}"
  local repo_url="$payload"
  local query=""
  local git_ref=""

  if [[ "$payload" == *"?"* ]]; then
    repo_url="${payload%%\?*}"
    query="${payload#*\?}"
  fi
  if [[ -z "$repo_url" ]]; then
    die "git source URI is missing repository URL: $uri"
  fi

  if [[ -n "$query" ]]; then
    local pair key value
    IFS='&' read -r -a pairs <<<"$query"
    for pair in "${pairs[@]}"; do
      key="${pair%%=*}"
      value=""
      if [[ "$pair" == *=* ]]; then
        value="${pair#*=}"
      fi
      if [[ "$key" == "ref" ]]; then
        git_ref="$value"
      fi
    done
  fi

  printf '%s\n%s\n' "$repo_url" "$git_ref"
}

checkout_git_ref() {
  local repo_dir="$1"
  local git_ref="$2"
  if [[ -z "$git_ref" ]]; then
    return 0
  fi

  if git -C "$repo_dir" show-ref --verify --quiet "refs/remotes/origin/$git_ref"; then
    git -C "$repo_dir" checkout -B "$git_ref" "origin/$git_ref"
    return 0
  fi

  if git -C "$repo_dir" show-ref --verify --quiet "refs/tags/$git_ref"; then
    git -C "$repo_dir" checkout --detach "refs/tags/$git_ref"
    return 0
  fi

  if git -C "$repo_dir" rev-parse --verify --quiet "$git_ref^{commit}" >/dev/null; then
    git -C "$repo_dir" checkout --detach "$git_ref"
    return 0
  fi

  if git -C "$repo_dir" fetch --prune origin "$git_ref" >/dev/null 2>&1; then
    git -C "$repo_dir" checkout --detach FETCH_HEAD
    return 0
  fi

  die "git ref not found in $repo_dir: $git_ref"
}

sync_git_repo() {
  local repo_url="$1"
  local repo_dir="$2"
  local git_ref="$3"

  if [[ -z "$repo_url" ]]; then
    return 0
  fi

  if [[ -d "$repo_dir/.git" ]]; then
    require_clean_git_repo "$repo_dir"
    git -C "$repo_dir" remote set-url origin "$repo_url"
    git -C "$repo_dir" fetch --prune origin
    if [[ -n "$git_ref" ]]; then
      checkout_git_ref "$repo_dir" "$git_ref"
      return 0
    fi

    # Intent: Handle detached-head lookups explicitly instead of suppressing
    # symbolic-ref errors, so branch-resolution fallbacks are observable.
    # Source: DI-008-20260412-122157 (TODO/008)
    local current_branch=""
    if current_branch="$(git -C "$repo_dir" symbolic-ref --quiet --short HEAD 2>/dev/null)"; then
      if [[ -n "$current_branch" ]]; then
        git -C "$repo_dir" pull --ff-only origin "$current_branch"
        return 0
      fi
    else
      echo "decomk bootstrap: detached HEAD in $repo_dir; trying origin default branch" >&2
    fi

    local origin_head
    origin_head="$(git -C "$repo_dir" remote show origin | sed -n 's/.*HEAD branch: //p' | head -n 1)"
    if [[ -n "$origin_head" ]]; then
      git -C "$repo_dir" checkout -B "$origin_head" "origin/$origin_head"
      git -C "$repo_dir" pull --ff-only origin "$origin_head"
      return 0
    fi

    git -C "$repo_dir" pull --ff-only
    return 0
  fi

  if [[ -e "$repo_dir" ]]; then
    die "path exists but is not a git repo: $repo_dir"
  fi

  mkdir -p "$(dirname "$repo_dir")"
  git clone "$repo_url" "$repo_dir"
  if [[ -n "$git_ref" ]]; then
    checkout_git_ref "$repo_dir" "$git_ref"
  fi
}

resolve_go_bin_dir() {
  local gobin
  gobin="$(go env GOBIN)"
  if [[ -n "$gobin" ]]; then
    printf '%s' "$gobin"
    return 0
  fi

  local gopath
  local gopath_first
  gopath="$(go env GOPATH)"
  gopath_first="${gopath%%:*}"
  if [[ -z "$gopath_first" ]]; then
    return 1
  fi
  printf '%s/bin' "$gopath_first"
}

install_decomk() {
  case "$DECOMK_TOOL_URI" in
    go:*)
      local install_spec="${DECOMK_TOOL_URI#go:}"
      if [[ -z "$install_spec" ]]; then
        die "go source URI must include module@version after go:"
      fi
      go install "$install_spec"
      ;;
    git:*)
      local parsed tool_repo_url tool_git_ref
      mapfile -t parsed < <(parse_git_uri "$DECOMK_TOOL_URI")
      tool_repo_url="${parsed[0]}"
      tool_git_ref="${parsed[1]:-}"
      local tool_src_dir="$DECOMK_HOME/src/decomk"
      sync_git_repo "$tool_repo_url" "$tool_src_dir" "$tool_git_ref"
      (cd "$tool_src_dir" && go install ./cmd/decomk)
      ;;
    *)
      die "invalid DECOMK_TOOL_URI=$DECOMK_TOOL_URI (expected go:... or git:...)"
      ;;
  esac
}

sync_conf_repo() {
  if [[ -z "$DECOMK_CONF_URI" ]]; then
    return 0
  fi

  case "$DECOMK_CONF_URI" in
    git:*)
      local parsed conf_repo_url conf_git_ref
      mapfile -t parsed < <(parse_git_uri "$DECOMK_CONF_URI")
      conf_repo_url="${parsed[0]}"
      conf_git_ref="${parsed[1]:-}"
      sync_git_repo "$conf_repo_url" "$DECOMK_HOME/conf" "$conf_git_ref"
      ;;
    *)
      die "invalid DECOMK_CONF_URI=$DECOMK_CONF_URI (expected git:...)"
      ;;
  esac
}

resolve_decomk_binary() {
  local go_bin_dir
  go_bin_dir="$(resolve_go_bin_dir)"
  if [[ -n "$go_bin_dir" ]] && [[ -x "$go_bin_dir/decomk" ]]; then
    printf '%s' "$go_bin_dir/decomk"
    return 0
  fi
  if command -v decomk >/dev/null 2>&1; then
    command -v decomk
    return 0
  fi
  return 1
}

resolve_phase_run_args() {
  case "$stage0_phase" in
    updateContent)
      printf '%s' "$DECOMK_UPDATE_CONTENT_RUN_ARGS"
      ;;
    postCreate)
      printf '%s' "$DECOMK_POST_CREATE_RUN_ARGS"
      ;;
    *)
      die "internal error: unsupported stage-0 phase while resolving run args: $stage0_phase"
      ;;
  esac
}

mkdir -p "$DECOMK_HOME" "$DECOMK_LOG_DIR"

install_decomk
sync_conf_repo

if [[ -z "$DECOMK_CONF_URI" ]] && [[ ! -f "$DECOMK_HOME/conf/decomk.conf" ]]; then
  die "no DECOMK_CONF_URI and no $DECOMK_HOME/conf/decomk.conf; skipping decomk run"
fi

decomk_bin="$(resolve_decomk_binary)" || {
  die "could not find installed decomk binary (tried go install target and PATH)"
}
phase_run_args="$(resolve_phase_run_args)"
if [[ -z "$phase_run_args" ]]; then
  die "resolved empty run args for stage-0 phase $stage0_phase"
fi

# Intent: Pass lifecycle phase as an explicit make tuple so config/make logic can
# separate prebuild/common behavior from runtime/user behavior without relying on
# ambiguous environment inference.
# Source: DI-001-20260416-223600 (TODO/001)
# shellcheck disable=SC2086
"$decomk_bin" run ${phase_run_args} DECOMK_STAGE0_PHASE="$stage0_phase"
