package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/stevegt/decomk/stage0"
)

const (
	branchSubcommandRender = "render"
	branchAutoChannel      = "auto"
	branchRegistryRelPath  = ".decomk/channels.json"
	branchDevcontainerPath = ".devcontainer/devcontainer.json"
)

// branchRenderHeader makes rendered JSONC files self-identifying while keeping
// the registry, not the generated file, as the policy source of truth.
//
// Intent: Warn maintainers that `.devcontainer/devcontainer.json` is a rendered
// devcontainer input whose channel values come from `.decomk/channels.json`.
// Source: DI-017-20260507-133819 (TODO/017)
const branchRenderHeader = `// generated by decomk branch render; do not edit directly
// Intent: Materialize branch-channel policy before devcontainer startup reads this file.
// Source: DI-017-20260507-133819 (TODO/017)
`

type branchRenderFlags struct {
	repoRoot string
	channel  string
	check    bool
}

type branchRegistry struct {
	Version      int                        `json:"version"`
	Devcontainer branchDevcontainerDefaults `json:"devcontainer"`
	Channels     map[string]branchChannel   `json:"channels"`
}

type branchDevcontainerDefaults struct {
	Path                 string            `json:"path"`
	Name                 string            `json:"name"`
	Build                *branchBuild      `json:"build,omitempty"`
	Image                string            `json:"image,omitempty"`
	OverrideCommand      *bool             `json:"overrideCommand,omitempty"`
	ContainerEnv         map[string]string `json:"containerEnv,omitempty"`
	UpdateRemoteUserUID  *bool             `json:"updateRemoteUserUID,omitempty"`
	UpdateContentCommand string            `json:"updateContentCommand,omitempty"`
	PostCreateCommand    string            `json:"postCreateCommand,omitempty"`
}

type branchChannel struct {
	Build        *branchBuild      `json:"build,omitempty"`
	Image        string            `json:"image,omitempty"`
	ContainerEnv map[string]string `json:"containerEnv,omitempty"`
}

type branchBuild struct {
	Dockerfile string `json:"dockerfile"`
	Context    string `json:"context"`
}

type branchRenderedDevcontainer struct {
	Name                 string            `json:"name"`
	Build                *branchBuild      `json:"build,omitempty"`
	Image                string            `json:"image,omitempty"`
	OverrideCommand      *bool             `json:"overrideCommand,omitempty"`
	ContainerEnv         map[string]string `json:"containerEnv,omitempty"`
	UpdateRemoteUserUID  *bool             `json:"updateRemoteUserUID,omitempty"`
	UpdateContentCommand string            `json:"updateContentCommand,omitempty"`
	PostCreateCommand    string            `json:"postCreateCommand,omitempty"`
}

// cmdBranch routes branch-channel commands.
func cmdBranch(args []string, stdout, stderr io.Writer) (int, error) {
	if len(args) == 0 {
		return 2, fmt.Errorf("branch subcommand required\n\n%s", branchUsage())
	}

	switch args[0] {
	case "-h", "-help", "--help", "help":
		if err := writeLine(stdout, branchUsage()); err != nil {
			return 1, err
		}
		return 0, nil
	case branchSubcommandRender:
		return cmdBranchRender(args[1:], stdout, stderr)
	default:
		return 2, fmt.Errorf("unknown branch subcommand: %s\n\n%s", args[0], branchUsage())
	}
}

func branchUsage() string {
	return `decomk branch - render/check branch-channel devcontainer config

Usage:
  decomk branch render [-check] [-repo-root <path>] [-channel <name|auto>]

Subcommands:
  render
      Render .devcontainer/devcontainer.json from .decomk/channels.json.
      With -check, compare the rendered content without writing.

Flags:
  -repo-root <path>  repository root containing .decomk/channels.json (default ".")
  -channel <name>    channel to render, or "auto" for current git branch (default "auto")
  -check             fail if the rendered devcontainer file is missing or stale`
}

func cmdBranchRender(args []string, stdout, stderr io.Writer) (int, error) {
	fs := flag.NewFlagSet("decomk branch render", flag.ContinueOnError)
	fs.SetOutput(stderr)

	flags := branchRenderFlags{
		repoRoot: ".",
		channel:  branchAutoChannel,
	}
	fs.StringVar(&flags.repoRoot, "repo-root", flags.repoRoot, "repository root containing .decomk/channels.json")
	fs.StringVar(&flags.channel, "channel", flags.channel, "channel to render, or auto for current git branch")
	fs.BoolVar(&flags.check, "check", false, "compare rendered devcontainer config without writing")
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0, nil
		}
		return 2, err
	}
	if len(fs.Args()) != 0 {
		return 2, fmt.Errorf("branch render does not accept positional args: %q", strings.Join(fs.Args(), " "))
	}

	repoRoot, err := filepath.Abs(flags.repoRoot)
	if err != nil {
		return 1, fmt.Errorf("abs repo root %q: %w", flags.repoRoot, err)
	}
	channelName := strings.TrimSpace(flags.channel)
	if channelName == "" {
		return 2, fmt.Errorf("channel cannot be empty")
	}
	if channelName == branchAutoChannel {
		channelName, err = detectBranchChannel(repoRoot)
		if err != nil {
			return 1, err
		}
	}

	renderedPath, renderedContent, err := renderBranchDevcontainer(repoRoot, channelName)
	if err != nil {
		return 1, err
	}

	if flags.check {
		existingContent, readErr := os.ReadFile(renderedPath)
		if readErr != nil {
			return 1, fmt.Errorf("read rendered devcontainer %s: %w", renderedPath, readErr)
		}
		if !bytes.Equal(existingContent, renderedContent) {
			return 1, fmt.Errorf("rendered devcontainer %s is stale for channel %q; run `decomk branch render -channel %s`", renderedPath, channelName, channelName)
		}
		if err := writeLine(stdout, "ok", renderedPath, "matches channel", channelName); err != nil {
			return 1, err
		}
		return 0, nil
	}

	if err := ensureParentDir(renderedPath); err != nil {
		return 1, err
	}
	if err := stage0.WriteFileAtomic(renderedPath, renderedContent, 0o644); err != nil {
		return 1, fmt.Errorf("write rendered devcontainer %s: %w", renderedPath, err)
	}
	if err := writeLine(stdout, "rendered", renderedPath, "for channel", channelName); err != nil {
		return 1, err
	}
	return 0, nil
}

// detectBranchChannel keeps "channel auto" aligned with the repo's current git
// branch so maintainers do not have to repeat the same branch name on every
// render/check invocation.
func detectBranchChannel(repoRoot string) (string, error) {
	output, err := exec.Command("git", "-C", repoRoot, "branch", "--show-current").CombinedOutput()
	if err != nil {
		compactOutput := strings.TrimSpace(string(output))
		if compactOutput == "" {
			return "", fmt.Errorf("detect git branch in %s: %w", repoRoot, err)
		}
		return "", fmt.Errorf("detect git branch in %s: %w: %s", repoRoot, err, compactOutput)
	}
	channelName := strings.TrimSpace(string(output))
	if channelName == "" {
		return "", fmt.Errorf("could not auto-detect channel from detached HEAD in %s; pass -channel explicitly", repoRoot)
	}
	return channelName, nil
}

func renderBranchDevcontainer(repoRoot, channelName string) (string, []byte, error) {
	registry, err := loadBranchRegistry(filepath.Join(repoRoot, branchRegistryRelPath))
	if err != nil {
		return "", nil, err
	}
	devcontainerPath, rendered, err := registry.render(channelName)
	if err != nil {
		return "", nil, err
	}
	return filepath.Join(repoRoot, devcontainerPath), rendered, nil
}

func loadBranchRegistry(path string) (*branchRegistry, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read branch registry %s: %w", path, err)
	}
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()

	var registry branchRegistry
	if err := decoder.Decode(&registry); err != nil {
		return nil, fmt.Errorf("parse branch registry %s: %w", path, err)
	}
	var trailingValue any
	if err := decoder.Decode(&trailingValue); !errors.Is(err, io.EOF) {
		return nil, fmt.Errorf("parse branch registry %s: trailing JSON values are not allowed", path)
	}
	if err := registry.validate(); err != nil {
		return nil, fmt.Errorf("validate branch registry %s: %w", path, err)
	}
	return &registry, nil
}

func (registry *branchRegistry) validate() error {
	if registry.Version != 1 {
		return fmt.Errorf("version must be 1")
	}
	if strings.TrimSpace(registry.Devcontainer.Name) == "" {
		return fmt.Errorf("devcontainer.name is required")
	}
	if len(registry.Channels) == 0 {
		return fmt.Errorf("channels must not be empty")
	}
	for channelName, channel := range registry.Channels {
		if strings.TrimSpace(channelName) == "" {
			return fmt.Errorf("channel names must not be empty")
		}
		if err := validateBranchSource(channel.Build, channel.Image); err != nil {
			return fmt.Errorf("channel %q: %w", channelName, err)
		}
	}
	return nil
}

// render applies channel-specific build/image and containerEnv overrides on top
// of repo-wide devcontainer defaults, then materializes the effective
// `.devcontainer/devcontainer.json` content that devcontainer tooling will read.
func (registry *branchRegistry) render(channelName string) (string, []byte, error) {
	channel, ok := registry.Channels[channelName]
	if !ok {
		return "", nil, fmt.Errorf("channel %q not found in registry", channelName)
	}

	targetPath := strings.TrimSpace(registry.Devcontainer.Path)
	if targetPath == "" {
		targetPath = branchDevcontainerPath
	}
	if filepath.IsAbs(targetPath) {
		return "", nil, fmt.Errorf("devcontainer.path must be relative: %s", targetPath)
	}

	buildSource := channel.Build
	imageSource := strings.TrimSpace(channel.Image)
	if buildSource == nil && imageSource == "" {
		buildSource = registry.Devcontainer.Build
		imageSource = strings.TrimSpace(registry.Devcontainer.Image)
	}
	if err := validateBranchSource(buildSource, imageSource); err != nil {
		return "", nil, err
	}

	containerEnv := mergeStringMaps(registry.Devcontainer.ContainerEnv, channel.ContainerEnv)
	if err := validateBranchToolURI(channelName, containerEnv); err != nil {
		return "", nil, err
	}

	devcontainer := branchRenderedDevcontainer{
		Name:                 strings.TrimSpace(registry.Devcontainer.Name),
		Build:                buildSource,
		Image:                imageSource,
		OverrideCommand:      registry.Devcontainer.OverrideCommand,
		ContainerEnv:         containerEnv,
		UpdateRemoteUserUID:  registry.Devcontainer.UpdateRemoteUserUID,
		UpdateContentCommand: strings.TrimSpace(registry.Devcontainer.UpdateContentCommand),
		PostCreateCommand:    strings.TrimSpace(registry.Devcontainer.PostCreateCommand),
	}
	if devcontainer.Build != nil {
		devcontainer.Image = ""
	}

	jsonContent, err := json.MarshalIndent(devcontainer, "", "  ")
	if err != nil {
		return "", nil, err
	}
	renderedContent := append([]byte(branchRenderHeader), jsonContent...)
	renderedContent = append(renderedContent, '\n')
	return targetPath, renderedContent, nil
}

func validateBranchSource(buildSource *branchBuild, imageSource string) error {
	if buildSource != nil && strings.TrimSpace(imageSource) != "" {
		return fmt.Errorf("set either build or image, not both")
	}
	if buildSource == nil && strings.TrimSpace(imageSource) == "" {
		return fmt.Errorf("set either build or image")
	}
	if buildSource != nil {
		if strings.TrimSpace(buildSource.Dockerfile) == "" {
			return fmt.Errorf("build.dockerfile is required")
		}
		if strings.TrimSpace(buildSource.Context) == "" {
			return fmt.Errorf("build.context is required")
		}
	}
	return nil
}

// validateBranchToolURI blocks promoted channels from following `@latest`, which
// would reintroduce tool drift after the registry has already pinned build/image
// and conf-repo refs per channel.
func validateBranchToolURI(channelName string, containerEnv map[string]string) error {
	if channelName != "testing" && channelName != "stable" {
		return nil
	}
	toolURI := strings.TrimSpace(containerEnv["DECOMK_TOOL_URI"])
	if toolURI == "" {
		return fmt.Errorf("channel %q requires DECOMK_TOOL_URI", channelName)
	}
	if strings.HasSuffix(toolURI, "@latest") {
		return fmt.Errorf("channel %q cannot use DECOMK_TOOL_URI ending in @latest", channelName)
	}
	return nil
}

func mergeStringMaps(base, overlay map[string]string) map[string]string {
	merged := map[string]string{}
	for key, value := range base {
		merged[key] = value
	}
	for key, value := range overlay {
		merged[key] = value
	}
	return merged
}

func ensureParentDir(path string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	return nil
}
