package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/stevegt/decomk/stage0"
	"github.com/tailscale/hujson"
)

const (
	branchSubcommandRender = "render"
	branchAutoChannel      = "auto"
	branchRegistryRelPath  = ".decomk/channels.json"
	branchDevcontainerPath = ".devcontainer/devcontainer.json"
)

// branchRenderHeader makes rendered JSONC files self-identifying while keeping
// the registry, not the generated file, as the policy source of truth.
//
// Intent: Warn maintainers that `.devcontainer/devcontainer.json` is a rendered
// devcontainer input whose channel values come from `.decomk/channels.json`.
// Source: DI-017-20260507-133819 (TODO/017)
const branchRenderHeader = `// generated by decomk branch render; do not edit directly
// Intent: Materialize branch-channel policy before devcontainer startup reads this file.
// Source: DI-017-20260507-133819 (TODO/017)
`

type branchRenderFlags struct {
	repoRoot string
	channel  string
	check    bool
}

type branchRegistry struct {
	Version      int                        `json:"version"`
	Devcontainer branchDevcontainerDefaults `json:"devcontainer"`
	Channels     map[string]branchChannel   `json:"channels"`
}

type branchDevcontainerDefaults struct {
	Path                 string              `json:"path"`
	Name                 string              `json:"name"`
	Comments             map[string][]string `json:"comments,omitempty"`
	Build                *branchBuild        `json:"build,omitempty"`
	Image                string              `json:"image,omitempty"`
	OverrideCommand      *bool               `json:"overrideCommand,omitempty"`
	ContainerEnv         map[string]string   `json:"containerEnv,omitempty"`
	UpdateRemoteUserUID  *bool               `json:"updateRemoteUserUID,omitempty"`
	UpdateContentCommand string              `json:"updateContentCommand,omitempty"`
	PostCreateCommand    string              `json:"postCreateCommand,omitempty"`
}

type branchChannel struct {
	Build        *branchBuild      `json:"build,omitempty"`
	Image        string            `json:"image,omitempty"`
	ContainerEnv map[string]string `json:"containerEnv,omitempty"`
}

type branchBuild struct {
	Dockerfile string `json:"dockerfile"`
	Context    string `json:"context"`
}

type branchRenderedDevcontainer struct {
	Name                 string            `json:"name"`
	Build                *branchBuild      `json:"build,omitempty"`
	Image                string            `json:"image,omitempty"`
	OverrideCommand      *bool             `json:"overrideCommand,omitempty"`
	ContainerEnv         map[string]string `json:"containerEnv,omitempty"`
	UpdateRemoteUserUID  *bool             `json:"updateRemoteUserUID,omitempty"`
	UpdateContentCommand string            `json:"updateContentCommand,omitempty"`
	PostCreateCommand    string            `json:"postCreateCommand,omitempty"`
}

type plannedBranchField struct {
	key string
}

// cmdBranch routes branch-channel commands.
func cmdBranch(args []string, stdout, stderr io.Writer) (int, error) {
	if len(args) == 0 {
		return 2, fmt.Errorf("branch subcommand required\n\n%s", branchUsage())
	}

	switch args[0] {
	case "-h", "-help", "--help", "help":
		if err := writeLine(stdout, branchUsage()); err != nil {
			return 1, err
		}
		return 0, nil
	case branchSubcommandRender:
		return cmdBranchRender(args[1:], stdout, stderr)
	default:
		return 2, fmt.Errorf("unknown branch subcommand: %s\n\n%s", args[0], branchUsage())
	}
}

func branchUsage() string {
	return `decomk branch - render/check branch-channel devcontainer config

Usage:
  decomk branch render [-check] [-repo-root <path>] [-channel <name|auto>]

Subcommands:
  render
      Render .devcontainer/devcontainer.json from .decomk/channels.json.
      With -check, compare the rendered content without writing.

Flags:
  -repo-root <path>  repository root containing .decomk/channels.json (default ".")
  -channel <name>    channel to render, or "auto" for current git branch (default "auto")
  -check             fail if the rendered devcontainer file is missing or stale`
}

func cmdBranchRender(args []string, stdout, stderr io.Writer) (int, error) {
	fs := flag.NewFlagSet("decomk branch render", flag.ContinueOnError)
	fs.SetOutput(stderr)

	flags := branchRenderFlags{
		repoRoot: ".",
		channel:  branchAutoChannel,
	}
	fs.StringVar(&flags.repoRoot, "repo-root", flags.repoRoot, "repository root containing .decomk/channels.json")
	fs.StringVar(&flags.channel, "channel", flags.channel, "channel to render, or auto for current git branch")
	fs.BoolVar(&flags.check, "check", false, "compare rendered devcontainer config without writing")
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0, nil
		}
		return 2, err
	}
	if len(fs.Args()) != 0 {
		return 2, fmt.Errorf("branch render does not accept positional args: %q", strings.Join(fs.Args(), " "))
	}

	repoRoot, err := filepath.Abs(flags.repoRoot)
	if err != nil {
		return 1, fmt.Errorf("abs repo root %q: %w", flags.repoRoot, err)
	}
	channelName := strings.TrimSpace(flags.channel)
	if channelName == "" {
		return 2, fmt.Errorf("channel cannot be empty")
	}
	if channelName == branchAutoChannel {
		channelName, err = detectBranchChannel(repoRoot)
		if err != nil {
			return 1, err
		}
	}

	renderedPath, renderedContent, err := renderBranchDevcontainer(repoRoot, channelName)
	if err != nil {
		return 1, err
	}

	if flags.check {
		existingContent, readErr := os.ReadFile(renderedPath)
		if readErr != nil {
			return 1, fmt.Errorf("read rendered devcontainer %s: %w", renderedPath, readErr)
		}
		if !bytes.Equal(existingContent, renderedContent) {
			return 1, fmt.Errorf("rendered devcontainer %s is stale for channel %q; run `decomk branch render -channel %s`", renderedPath, channelName, channelName)
		}
		if err := writeLine(stdout, "ok", renderedPath, "matches channel", channelName); err != nil {
			return 1, err
		}
		return 0, nil
	}

	if err := ensureParentDir(renderedPath); err != nil {
		return 1, err
	}
	if err := stage0.WriteFileAtomic(renderedPath, renderedContent, 0o644); err != nil {
		return 1, fmt.Errorf("write rendered devcontainer %s: %w", renderedPath, err)
	}
	if err := writeLine(stdout, "rendered", renderedPath, "for channel", channelName); err != nil {
		return 1, err
	}
	return 0, nil
}

// detectBranchChannel keeps "channel auto" aligned with the repo's current git
// branch so maintainers do not have to repeat the same branch name on every
// render/check invocation.
func detectBranchChannel(repoRoot string) (string, error) {
	output, err := exec.Command("git", "-C", repoRoot, "branch", "--show-current").CombinedOutput()
	if err != nil {
		compactOutput := strings.TrimSpace(string(output))
		if compactOutput == "" {
			return "", fmt.Errorf("detect git branch in %s: %w", repoRoot, err)
		}
		return "", fmt.Errorf("detect git branch in %s: %w: %s", repoRoot, err, compactOutput)
	}
	channelName := strings.TrimSpace(string(output))
	if channelName == "" {
		return "", fmt.Errorf("could not auto-detect channel from detached HEAD in %s; pass -channel explicitly", repoRoot)
	}
	return channelName, nil
}

func renderBranchDevcontainer(repoRoot, channelName string) (string, []byte, error) {
	registry, err := loadBranchRegistry(filepath.Join(repoRoot, branchRegistryRelPath))
	if err != nil {
		return "", nil, err
	}
	devcontainerPath, rendered, err := registry.render(channelName)
	if err != nil {
		return "", nil, err
	}
	return filepath.Join(repoRoot, devcontainerPath), rendered, nil
}

func loadBranchRegistry(path string) (*branchRegistry, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read branch registry %s: %w", path, err)
	}
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()

	var registry branchRegistry
	if err := decoder.Decode(&registry); err != nil {
		return nil, fmt.Errorf("parse branch registry %s: %w", path, err)
	}
	var trailingValue any
	if err := decoder.Decode(&trailingValue); !errors.Is(err, io.EOF) {
		return nil, fmt.Errorf("parse branch registry %s: trailing JSON values are not allowed", path)
	}
	if err := registry.validate(); err != nil {
		return nil, fmt.Errorf("validate branch registry %s: %w", path, err)
	}
	return &registry, nil
}

func (registry *branchRegistry) validate() error {
	if registry.Version != 1 {
		return fmt.Errorf("version must be 1")
	}
	if strings.TrimSpace(registry.Devcontainer.Name) == "" {
		return fmt.Errorf("devcontainer.name is required")
	}
	if len(registry.Channels) == 0 {
		return fmt.Errorf("channels must not be empty")
	}
	for channelName, channel := range registry.Channels {
		if strings.TrimSpace(channelName) == "" {
			return fmt.Errorf("channel names must not be empty")
		}
		if err := validateBranchSource(channel.Build, channel.Image); err != nil {
			return fmt.Errorf("channel %q: %w", channelName, err)
		}
	}
	return nil
}

// render applies channel-specific build/image and containerEnv overrides on top
// of repo-wide devcontainer defaults, then materializes the effective
// `.devcontainer/devcontainer.json` content that devcontainer tooling will read.
func (registry *branchRegistry) render(channelName string) (string, []byte, error) {
	channel, ok := registry.Channels[channelName]
	if !ok {
		return "", nil, fmt.Errorf("channel %q not found in registry", channelName)
	}

	targetPath := strings.TrimSpace(registry.Devcontainer.Path)
	if targetPath == "" {
		targetPath = branchDevcontainerPath
	}
	if filepath.IsAbs(targetPath) {
		return "", nil, fmt.Errorf("devcontainer.path must be relative: %s", targetPath)
	}

	buildSource := channel.Build
	imageSource := strings.TrimSpace(channel.Image)
	if buildSource == nil && imageSource == "" {
		buildSource = registry.Devcontainer.Build
		imageSource = strings.TrimSpace(registry.Devcontainer.Image)
	}
	if err := validateBranchSource(buildSource, imageSource); err != nil {
		return "", nil, err
	}

	containerEnv := mergeStringMaps(registry.Devcontainer.ContainerEnv, channel.ContainerEnv)
	if err := validateBranchToolURI(channelName, containerEnv); err != nil {
		return "", nil, err
	}

	devcontainer := branchRenderedDevcontainer{
		Name:                 strings.TrimSpace(registry.Devcontainer.Name),
		Build:                buildSource,
		Image:                imageSource,
		OverrideCommand:      registry.Devcontainer.OverrideCommand,
		ContainerEnv:         containerEnv,
		UpdateRemoteUserUID:  registry.Devcontainer.UpdateRemoteUserUID,
		UpdateContentCommand: strings.TrimSpace(registry.Devcontainer.UpdateContentCommand),
		PostCreateCommand:    strings.TrimSpace(registry.Devcontainer.PostCreateCommand),
	}
	if devcontainer.Build != nil {
		devcontainer.Image = ""
	}

	plannedFields := planBranchFields(devcontainer)
	fieldKeys := make([]string, 0, len(plannedFields))
	for _, plannedField := range plannedFields {
		fieldKeys = append(fieldKeys, plannedField.key)
	}
	if err := validateCommentKeys(registry.Devcontainer.Comments, fieldKeys, channelName); err != nil {
		return "", nil, err
	}
	renderedContent, err := writeBranchDevcontainer(devcontainer, plannedFields, registry.Devcontainer.Comments)
	if err != nil {
		return "", nil, err
	}
	return targetPath, renderedContent, nil
}

// planBranchFields keeps comment targeting aligned with the exact set and order
// of top-level keys that the current renderer will emit for the selected
// channel.
//
// Intent: Validate registry-owned comment targets against the actual rendered
// top-level devcontainer fields so generated JSONC stays deterministic and
// comment placement cannot silently drift.
// Source: DI-018-20260507-204852 (TODO/018)
func planBranchFields(devcontainer branchRenderedDevcontainer) []plannedBranchField {
	plannedFields := []plannedBranchField{
		{key: "name"},
	}
	if devcontainer.Build != nil {
		plannedFields = append(plannedFields, plannedBranchField{key: "build"})
	} else if strings.TrimSpace(devcontainer.Image) != "" {
		plannedFields = append(plannedFields, plannedBranchField{key: "image"})
	}
	if devcontainer.OverrideCommand != nil {
		plannedFields = append(plannedFields, plannedBranchField{key: "overrideCommand"})
	}
	if len(devcontainer.ContainerEnv) != 0 {
		plannedFields = append(plannedFields, plannedBranchField{key: "containerEnv"})
	}
	if devcontainer.UpdateRemoteUserUID != nil {
		plannedFields = append(plannedFields, plannedBranchField{key: "updateRemoteUserUID"})
	}
	if strings.TrimSpace(devcontainer.UpdateContentCommand) != "" {
		plannedFields = append(plannedFields, plannedBranchField{key: "updateContentCommand"})
	}
	if strings.TrimSpace(devcontainer.PostCreateCommand) != "" {
		plannedFields = append(plannedFields, plannedBranchField{key: "postCreateCommand"})
	}
	return plannedFields
}

func validateBranchSource(buildSource *branchBuild, imageSource string) error {
	if buildSource != nil && strings.TrimSpace(imageSource) != "" {
		return fmt.Errorf("set either build or image, not both")
	}
	if buildSource == nil && strings.TrimSpace(imageSource) == "" {
		return fmt.Errorf("set either build or image")
	}
	if buildSource != nil {
		if strings.TrimSpace(buildSource.Dockerfile) == "" {
			return fmt.Errorf("build.dockerfile is required")
		}
		if strings.TrimSpace(buildSource.Context) == "" {
			return fmt.Errorf("build.context is required")
		}
	}
	return nil
}

// validateCommentKeys rejects registry-owned comment targets that do not map to
// a field actually rendered for the selected channel.
//
// Intent: Fail fast when `.decomk/channels.json` tries to preserve DI/comment
// context for a field that is absent from the rendered devcontainer file.
// Source: DI-018-20260507-204852 (TODO/018)
func validateCommentKeys(comments map[string][]string, fieldKeys []string, channelName string) error {
	if len(comments) == 0 {
		return nil
	}
	allowedKeys := make(map[string]struct{}, len(fieldKeys))
	for _, fieldKey := range fieldKeys {
		allowedKeys[fieldKey] = struct{}{}
	}
	for commentKey := range comments {
		if _, ok := allowedKeys[commentKey]; ok {
			continue
		}
		return fmt.Errorf("comment key %q does not match a rendered field for channel %q", commentKey, channelName)
	}
	return nil
}

// validateBranchToolURI blocks promoted channels from following `@latest`, which
// would reintroduce tool drift after the registry has already pinned build/image
// and conf-repo refs per channel.
func validateBranchToolURI(channelName string, containerEnv map[string]string) error {
	if channelName != "testing" && channelName != "stable" {
		return nil
	}
	toolURI := strings.TrimSpace(containerEnv["DECOMK_TOOL_URI"])
	if toolURI == "" {
		return fmt.Errorf("channel %q requires DECOMK_TOOL_URI", channelName)
	}
	if strings.HasSuffix(toolURI, "@latest") {
		return fmt.Errorf("channel %q cannot use DECOMK_TOOL_URI ending in @latest", channelName)
	}
	return nil
}

// writeBranchDevcontainer preserves the current generated devcontainer layout,
// then uses HuJSON AST mutation to inject registry-owned JSONC comment blocks
// immediately before matching top-level fields.
//
// Intent: Keep the existing rendered JSON shape stable while allowing downstream
// repos to preserve DI/comment provenance inside generated devcontainer files.
// Source: DI-018-20260507-204852 (TODO/018)
func writeBranchDevcontainer(devcontainer branchRenderedDevcontainer, plannedFields []plannedBranchField, comments map[string][]string) ([]byte, error) {
	jsonContent, err := json.MarshalIndent(devcontainer, "", "  ")
	if err != nil {
		return nil, err
	}
	renderedContent := append([]byte(branchRenderHeader), jsonContent...)
	renderedContent = append(renderedContent, '\n')
	if len(comments) == 0 {
		return renderedContent, nil
	}

	parsedContent, err := hujson.Parse(renderedContent)
	if err != nil {
		return nil, fmt.Errorf("parse rendered devcontainer as hujson: %w", err)
	}
	object, ok := parsedContent.Value.(*hujson.Object)
	if !ok {
		return nil, fmt.Errorf("rendered devcontainer root is not a hujson object")
	}
	fieldIndexes, err := plannedBranchFieldIndexes(object, plannedFields)
	if err != nil {
		return nil, err
	}
	for _, plannedField := range plannedFields {
		commentLines, ok := comments[plannedField.key]
		if !ok {
			continue
		}
		memberIndex, ok := fieldIndexes[plannedField.key]
		if !ok {
			return nil, fmt.Errorf("rendered devcontainer field %q missing from hujson object", plannedField.key)
		}
		member := object.Members[memberIndex]
		member.Name.BeforeExtra = branchCommentExtra(member.Name.BeforeExtra, commentLines)
		object.Members[memberIndex] = member
	}
	parsedContent.Value = object
	packedContent := parsedContent.Pack()
	if len(packedContent) == 0 || packedContent[len(packedContent)-1] != '\n' {
		packedContent = append(packedContent, '\n')
	}
	return packedContent, nil
}

// plannedBranchFieldIndexes maps the actual HuJSON object members back to the
// planned top-level field keys so comment injection can target the exact member
// that will be written to disk.
func plannedBranchFieldIndexes(object *hujson.Object, plannedFields []plannedBranchField) (map[string]int, error) {
	fieldIndexes := make(map[string]int, len(object.Members))
	for memberIndex, member := range object.Members {
		fieldKey, err := branchObjectMemberKey(member)
		if err != nil {
			return nil, err
		}
		fieldIndexes[fieldKey] = memberIndex
	}
	for _, plannedField := range plannedFields {
		if _, ok := fieldIndexes[plannedField.key]; ok {
			continue
		}
		return nil, fmt.Errorf("rendered devcontainer field %q missing from hujson object", plannedField.key)
	}
	return fieldIndexes, nil
}

func branchObjectMemberKey(member hujson.ObjectMember) (string, error) {
	nameLiteral, ok := member.Name.Value.(hujson.Literal)
	if !ok {
		return "", fmt.Errorf("rendered devcontainer member name is not a string literal")
	}
	var fieldKey string
	if err := json.Unmarshal([]byte(nameLiteral), &fieldKey); err != nil {
		return "", fmt.Errorf("decode rendered devcontainer member name: %w", err)
	}
	return fieldKey, nil
}

// branchCommentExtra preserves the existing field indentation and inserts each
// configured registry comment line immediately before the matching JSON field.
func branchCommentExtra(existing hujson.Extra, commentLines []string) hujson.Extra {
	if len(commentLines) == 0 {
		return existing
	}
	existingText := string(existing)
	linePrefix := ""
	indent := existingText
	newlineIndex := strings.LastIndexByte(existingText, '\n')
	if newlineIndex >= 0 {
		linePrefix = existingText[:newlineIndex+1]
		indent = existingText[newlineIndex+1:]
	}
	var builder strings.Builder
	builder.WriteString(linePrefix)
	for _, commentLine := range commentLines {
		builder.WriteString(indent)
		builder.WriteString("// ")
		builder.WriteString(commentLine)
		builder.WriteByte('\n')
	}
	builder.WriteString(indent)
	return hujson.Extra(builder.String())
}

func mergeStringMaps(base, overlay map[string]string) map[string]string {
	merged := map[string]string{}
	for key, value := range base {
		merged[key] = value
	}
	for key, value := range overlay {
		merged[key] = value
	}
	return merged
}

func ensureParentDir(path string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	return nil
}
