package main

import _ "embed"

var (
	// initDevcontainerJSONTemplate is the stage-0 template for .devcontainer/devcontainer.json.
	//
	//go:embed templates/devcontainer.json.tmpl
	initDevcontainerJSONTemplate string

	// initConsumerDevcontainerJSONTemplate is the minimal image-consumer template
	// for .devcontainer/devcontainer.json generated by `decomk init`.
	//
	//go:embed templates/consumer.devcontainer.json.tmpl
	initConsumerDevcontainerJSONTemplate string

	// initStage0ScriptTemplate is the stage-0 template for .devcontainer/decomk-stage0.sh.
	//
	//go:embed templates/decomk-stage0.sh.tmpl
	initStage0ScriptTemplate string
)
