#!/usr/bin/env bash

# GENERATED BY decomk stage-0 templates. DO NOT EDIT.
# Customize container behavior through shared decomk.conf and Makefile content.

set -Eeuo pipefail

die() {
  echo "decomk bootstrap: $*" >&2
  return 1
}

# Intent: Expose explicit lifecycle phases through one stage-0 script so
# devcontainer hooks can call the same bootstrap logic with clear phase inputs.
# Source: DI-001-20260416-223600 (TODO/001)
stage0_phase="postCreate"
if [[ $# -gt 0 ]]; then
  stage0_phase="$1"
  shift
fi
case "$stage0_phase" in
  updateContent|postCreate)
    ;;
  *)
    die "invalid stage-0 phase: $stage0_phase (expected updateContent or postCreate)"
    ;;
esac

# Intent: Implement generic stage-0 bootstrap with URI-based source expressions
# so tool/config acquisition is explicit, deterministic, and shared between
# generated examples and `decomk init` scaffolds.
# Source: DI-001-20260412-170500 (TODO/001)
DECOMK_HOME="${DECOMK_HOME:-/var/decomk}"
DECOMK_LOG_DIR="${DECOMK_LOG_DIR:-/var/log/decomk}"
DECOMK_TOOL_URI="${DECOMK_TOOL_URI:-go:github.com/stevegt/decomk/cmd/decomk@latest}"
DECOMK_CONF_URI="${DECOMK_CONF_URI:-}"
DECOMK_FAIL_NOBOOT="${DECOMK_FAIL_NOBOOT:-false}"
DECOMK_STAGE0_PHASE="$stage0_phase"

export DECOMK_HOME DECOMK_LOG_DIR DECOMK_TOOL_URI DECOMK_CONF_URI DECOMK_FAIL_NOBOOT
export DECOMK_STAGE0_PHASE

stage0_runtime_log=""
stage0_fail_no_boot=""
stage0_error_step="startup"
stage0_error_active=0
stage0_failure_dir="$DECOMK_HOME/stage0/failure"
stage0_failure_marker="$stage0_failure_dir/latest-${stage0_phase}.marker"
stage0_failure_log="$stage0_failure_dir/latest-${stage0_phase}.log"
stage0_motd_hint="/etc/motd.d/80-decomk-stage0"
stage0_motd_fallback="$stage0_failure_dir/motd.txt"

timestamp_utc() {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

normalize_fail_no_boot() {
  local raw="$1"
  local normalized="${raw,,}"
  case "$normalized" in
    ""|0|false|no|off)
      printf '%s' "false"
      ;;
    1|true|yes|on)
      printf '%s' "true"
      ;;
    *)
      die "invalid DECOMK_FAIL_NOBOOT=$raw (expected one of: true,false,1,0,yes,no,on,off)"
      ;;
  esac
}

setup_runtime_log() {
  stage0_runtime_log="$DECOMK_LOG_DIR/stage0-${stage0_phase}.log"
  if ! : >"$stage0_runtime_log"; then
    die "unable to create runtime log file: $stage0_runtime_log"
  fi
  exec > >(tee -a "$stage0_runtime_log") 2>&1
  echo "decomk bootstrap: runtime log: $stage0_runtime_log"
}

emit_stage0_identity_marker() {
  local stage0_uid stage0_user
  stage0_uid="$(id -u)"
  stage0_user="$(id -un)"
  export DECOMK_STAGE0_UID="$stage0_uid"
  export DECOMK_STAGE0_USER="$stage0_user"
  # Intent: Emit explicit stage-0 identity markers for selftest evidence so
  # operators can prove which user executes stage-0 vs which user executes make.
  # Source: DI-007-20260423-180202 (TODO/007)
  echo "SELFTEST PASS stage0-id phase=$stage0_phase uid=$stage0_uid user=$stage0_user"
}

write_stage0_failure_artifacts() {
  local rc="$1"
  local line="$2"
  local now
  now="$(timestamp_utc)"

  if mkdir -p "$stage0_failure_dir"; then
    echo "decomk bootstrap: wrote failure dir: $stage0_failure_dir"
  else
    local mkdir_rc="$?"
    echo "decomk bootstrap: failed to create failure dir: $stage0_failure_dir (rc=$mkdir_rc)" >&2
  fi

  if [[ -n "$stage0_runtime_log" ]] && [[ -f "$stage0_runtime_log" ]]; then
    if cp "$stage0_runtime_log" "$stage0_failure_log"; then
      echo "decomk bootstrap: wrote failure log: $stage0_failure_log"
    else
      local cp_rc="$?"
      echo "decomk bootstrap: failed to copy failure log: $stage0_failure_log (rc=$cp_rc)" >&2
    fi
  else
    if printf '%s\n' "decomk bootstrap: no runtime log file was captured" >"$stage0_failure_log"; then
      echo "decomk bootstrap: wrote synthetic failure log: $stage0_failure_log"
    else
      local synthetic_log_rc="$?"
      echo "decomk bootstrap: failed to write synthetic failure log: $stage0_failure_log (rc=$synthetic_log_rc)" >&2
    fi
  fi

  local marker_text
  marker_text="$(cat <<EOF
timestamp=$now
phase=$stage0_phase
step=$stage0_error_step
line=$line
exit_code=$rc
decomk_fail_noboot=$stage0_fail_no_boot
decomk_home=$DECOMK_HOME
decomk_log_dir=$DECOMK_LOG_DIR
decomk_tool_uri=$DECOMK_TOOL_URI
decomk_conf_uri=$DECOMK_CONF_URI
runtime_log=$stage0_runtime_log
EOF
)"
  if printf '%s\n' "$marker_text" >"$stage0_failure_marker"; then
    echo "decomk bootstrap: wrote failure marker: $stage0_failure_marker"
  else
    local marker_rc="$?"
    echo "decomk bootstrap: failed to write failure marker: $stage0_failure_marker (rc=$marker_rc)" >&2
  fi

  local motd_text
  motd_text="decomk stage-0 warning (${stage0_phase}): step '${stage0_error_step}' failed (rc=${rc}); see ${stage0_failure_marker} and ${stage0_failure_log}"
  local wrote_motd=1
  if [[ -d /etc/motd.d ]] && [[ -w /etc/motd.d ]]; then
    if printf '%s\n' "$motd_text" >"$stage0_motd_hint"; then
      echo "decomk bootstrap: wrote MOTD hint: $stage0_motd_hint"
      wrote_motd=0
    else
      local motd_rc="$?"
      echo "decomk bootstrap: failed to write MOTD hint: $stage0_motd_hint (rc=$motd_rc)" >&2
    fi
  elif [[ -f "$stage0_motd_hint" ]] && [[ -w "$stage0_motd_hint" ]]; then
    if printf '%s\n' "$motd_text" >"$stage0_motd_hint"; then
      echo "decomk bootstrap: updated MOTD hint: $stage0_motd_hint"
      wrote_motd=0
    else
      local motd_file_rc="$?"
      echo "decomk bootstrap: failed to update MOTD hint: $stage0_motd_hint (rc=$motd_file_rc)" >&2
    fi
  else
    echo "decomk bootstrap: /etc/motd.d not writable; writing fallback hint under DECOMK_HOME" >&2
  fi

  if [[ "$wrote_motd" -ne 0 ]]; then
    if printf '%s\n' "$motd_text" >"$stage0_motd_fallback"; then
      echo "decomk bootstrap: wrote fallback hint: $stage0_motd_fallback"
    else
      local fallback_rc="$?"
      echo "decomk bootstrap: failed to write fallback hint: $stage0_motd_fallback (rc=$fallback_rc)" >&2
    fi
  fi
}

clear_stage0_failure_artifacts() {
  if [[ -f "$stage0_failure_marker" ]]; then
    if rm -f "$stage0_failure_marker"; then
      echo "decomk bootstrap: cleared stale failure marker: $stage0_failure_marker"
    else
      local marker_clear_rc="$?"
      echo "decomk bootstrap: failed to clear stale failure marker: $stage0_failure_marker (rc=$marker_clear_rc)" >&2
    fi
  fi
  if [[ -f "$stage0_failure_log" ]]; then
    if rm -f "$stage0_failure_log"; then
      echo "decomk bootstrap: cleared stale failure log: $stage0_failure_log"
    else
      local log_clear_rc="$?"
      echo "decomk bootstrap: failed to clear stale failure log: $stage0_failure_log (rc=$log_clear_rc)" >&2
    fi
  fi
  if [[ -f "$stage0_motd_hint" ]]; then
    if rm -f "$stage0_motd_hint"; then
      echo "decomk bootstrap: cleared stale MOTD hint: $stage0_motd_hint"
    else
      local motd_clear_rc="$?"
      echo "decomk bootstrap: failed to clear stale MOTD hint: $stage0_motd_hint (rc=$motd_clear_rc)" >&2
    fi
  fi
  if [[ -f "$stage0_motd_fallback" ]]; then
    if rm -f "$stage0_motd_fallback"; then
      echo "decomk bootstrap: cleared fallback hint: $stage0_motd_fallback"
    else
      local fallback_clear_rc="$?"
      echo "decomk bootstrap: failed to clear fallback hint: $stage0_motd_fallback (rc=$fallback_clear_rc)" >&2
    fi
  fi
}

require_root_stage0() {
  if [[ "$(id -u)" -eq 0 ]]; then
    return 0
  fi
  if [[ "${DECOMK_STAGE0_ESCALATED:-}" == "1" ]]; then
    die "stage-0 root escalation failed: already retried with sudo -n -E"
  fi
  if ! command -v sudo >/dev/null 2>&1; then
    die "stage-0 requires root but sudo is not in PATH"
  fi

  # Intent: Centralize privilege escalation at stage-0 startup so decomk itself
  # does not need to carry sudo fallback logic for make execution.
  # Source: DI-001-20260424-200248 (TODO/001)
  export DECOMK_STAGE0_ESCALATED=1
  exec sudo -n -E -- bash "$0" "$stage0_phase" "$@"
}

stage0_error_handler() {
  local rc="$1"
  local line="$2"

  if [[ "$stage0_error_active" -ne 0 ]]; then
    exit "$rc"
  fi
  stage0_error_active=1
  trap - ERR
  set +e

  # Intent: Keep stage-0 failure handling explicit and operator-visible by always
  # writing deterministic marker/log artifacts, then honoring DECOMK_FAIL_NOBOOT
  # to choose non-blocking continuation vs hard startup failure.
  # Source: DI-012-20260423-045339 (TODO/012)
  write_stage0_failure_artifacts "$rc" "$line"

  if [[ "$stage0_fail_no_boot" == "true" ]]; then
    echo "decomk bootstrap: DECOMK_FAIL_NOBOOT=true; exiting non-zero (rc=$rc)" >&2
    exit "$rc"
  fi
  echo "decomk bootstrap: warning: stage-0 failed (rc=$rc) but continuing boot because DECOMK_FAIL_NOBOOT=false" >&2
  exit 0
}

require_clean_git_repo() {
  local repo_dir="$1"
  if [[ -n "$(git -C "$repo_dir" status --porcelain --untracked-files=normal)" ]]; then
    die "git repo has uncommitted changes: $repo_dir"
  fi
}

parse_git_uri() {
  local uri="$1"
  if [[ "$uri" != git:* ]]; then
    die "git source URI must start with git: (got: $uri)"
  fi

  local payload="${uri#git:}"
  local repo_url="$payload"
  local query=""
  local git_ref=""

  if [[ "$payload" == *"?"* ]]; then
    repo_url="${payload%%\?*}"
    query="${payload#*\?}"
  fi
  if [[ -z "$repo_url" ]]; then
    die "git source URI is missing repository URL: $uri"
  fi

  if [[ -n "$query" ]]; then
    local pair key value
    IFS='&' read -r -a pairs <<<"$query"
    for pair in "${pairs[@]}"; do
      key="${pair%%=*}"
      value=""
      if [[ "$pair" == *=* ]]; then
        value="${pair#*=}"
      fi
      if [[ "$key" == "ref" ]]; then
        git_ref="$value"
      fi
    done
  fi

  printf '%s\n%s\n' "$repo_url" "$git_ref"
}

checkout_git_ref() {
  local repo_dir="$1"
  local git_ref="$2"
  if [[ -z "$git_ref" ]]; then
    return 0
  fi

  if git -C "$repo_dir" show-ref --verify --quiet "refs/remotes/origin/$git_ref"; then
    git -C "$repo_dir" checkout -B "$git_ref" "origin/$git_ref"
    return 0
  fi

  if git -C "$repo_dir" show-ref --verify --quiet "refs/tags/$git_ref"; then
    git -C "$repo_dir" checkout --detach "refs/tags/$git_ref"
    return 0
  fi

  if git -C "$repo_dir" rev-parse --verify --quiet "$git_ref^{commit}" >/dev/null; then
    git -C "$repo_dir" checkout --detach "$git_ref"
    return 0
  fi

  if git -C "$repo_dir" fetch --prune origin "$git_ref" >/dev/null 2>&1; then
    git -C "$repo_dir" checkout --detach FETCH_HEAD
    return 0
  fi

  die "git ref not found in $repo_dir: $git_ref"
}

sync_git_repo() {
  local repo_url="$1"
  local repo_dir="$2"
  local git_ref="$3"

  if [[ -z "$repo_url" ]]; then
    return 0
  fi

  if [[ -d "$repo_dir/.git" ]]; then
    require_clean_git_repo "$repo_dir"
    git -C "$repo_dir" remote set-url origin "$repo_url"
    git -C "$repo_dir" fetch --prune origin
    if [[ -n "$git_ref" ]]; then
      checkout_git_ref "$repo_dir" "$git_ref"
      return 0
    fi

    # Intent: Handle detached-head lookups explicitly instead of suppressing
    # symbolic-ref errors, so branch-resolution fallbacks are observable.
    # Source: DI-008-20260412-122157 (TODO/008)
    local current_branch=""
    if current_branch="$(git -C "$repo_dir" symbolic-ref --quiet --short HEAD 2>/dev/null)"; then
      if [[ -n "$current_branch" ]]; then
        git -C "$repo_dir" pull --ff-only origin "$current_branch"
        return 0
      fi
    else
      echo "decomk bootstrap: detached HEAD in $repo_dir; trying origin default branch" >&2
    fi

    local origin_head
    origin_head="$(git -C "$repo_dir" remote show origin | sed -n 's/.*HEAD branch: //p' | head -n 1)"
    if [[ -n "$origin_head" ]]; then
      git -C "$repo_dir" checkout -B "$origin_head" "origin/$origin_head"
      git -C "$repo_dir" pull --ff-only origin "$origin_head"
      return 0
    fi

    git -C "$repo_dir" pull --ff-only
    return 0
  fi

  if [[ -e "$repo_dir" ]]; then
    die "path exists but is not a git repo: $repo_dir"
  fi

  mkdir -p "$(dirname "$repo_dir")"
  git clone "$repo_url" "$repo_dir"
  if [[ -n "$git_ref" ]]; then
    checkout_git_ref "$repo_dir" "$git_ref"
  fi
}

resolve_go_bin_dir() {
  local gobin
  gobin="$(go env GOBIN)"
  if [[ -n "$gobin" ]]; then
    printf '%s' "$gobin"
    return 0
  fi

  local gopath
  local gopath_first
  gopath="$(go env GOPATH)"
  gopath_first="${gopath%%:*}"
  if [[ -z "$gopath_first" ]]; then
    return 1
  fi
  printf '%s/bin' "$gopath_first"
}

install_decomk() {
  case "$DECOMK_TOOL_URI" in
    go:*)
      local install_spec="${DECOMK_TOOL_URI#go:}"
      if [[ -z "$install_spec" ]]; then
        die "go source URI must include module@version after go:"
      fi
      go install "$install_spec"
      ;;
    git:*)
      local parsed tool_repo_url tool_git_ref
      mapfile -t parsed < <(parse_git_uri "$DECOMK_TOOL_URI")
      tool_repo_url="${parsed[0]}"
      tool_git_ref="${parsed[1]:-}"
      local tool_src_dir="$DECOMK_HOME/src/decomk"
      sync_git_repo "$tool_repo_url" "$tool_src_dir" "$tool_git_ref"
      (cd "$tool_src_dir" && go install ./cmd/decomk)
      ;;
    *)
      die "invalid DECOMK_TOOL_URI=$DECOMK_TOOL_URI (expected go:... or git:...)"
      ;;
  esac
}

sync_conf_repo() {
  if [[ -z "$DECOMK_CONF_URI" ]]; then
    return 0
  fi

  case "$DECOMK_CONF_URI" in
    git:*)
      local parsed conf_repo_url conf_git_ref
      mapfile -t parsed < <(parse_git_uri "$DECOMK_CONF_URI")
      conf_repo_url="${parsed[0]}"
      conf_git_ref="${parsed[1]:-}"
      sync_git_repo "$conf_repo_url" "$DECOMK_HOME/conf" "$conf_git_ref"
      ;;
    *)
      die "invalid DECOMK_CONF_URI=$DECOMK_CONF_URI (expected git:...)"
      ;;
  esac
}

resolve_decomk_binary() {
  local go_bin_dir
  go_bin_dir="$(resolve_go_bin_dir)"
  if [[ -n "$go_bin_dir" ]] && [[ -x "$go_bin_dir/decomk" ]]; then
    printf '%s' "$go_bin_dir/decomk"
    return 0
  fi
  if command -v decomk >/dev/null 2>&1; then
    command -v decomk
    return 0
  fi
  return 1
}

stage0_fail_no_boot="$(normalize_fail_no_boot "$DECOMK_FAIL_NOBOOT")"
trap 'stage0_error_handler "$?" "$LINENO"' ERR

stage0_error_step="require-root"
require_root_stage0 "$@"

stage0_error_step="prepare-paths"
mkdir -p "$DECOMK_HOME" "$DECOMK_LOG_DIR"

stage0_error_step="configure-runtime-log"
setup_runtime_log

stage0_error_step="stage0-identity"
emit_stage0_identity_marker

stage0_error_step="install-decomk"
install_decomk

stage0_error_step="sync-conf-repo"
sync_conf_repo

stage0_error_step="validate-conf-availability"
if [[ -z "$DECOMK_CONF_URI" ]] && [[ ! -f "$DECOMK_HOME/conf/decomk.conf" ]]; then
  die "no DECOMK_CONF_URI and no $DECOMK_HOME/conf/decomk.conf; skipping decomk run"
fi

stage0_error_step="resolve-decomk-binary"
decomk_bin="$(resolve_decomk_binary)" || {
  die "could not find installed decomk binary (tried go install target and PATH)"
}
action_args=("$@")
if [[ ${#action_args[@]} -eq 0 ]]; then
  action_args=("$stage0_phase")
fi

# Intent: Pass lifecycle phase as the explicit decomk action selector while
# exporting DECOMK_STAGE0_PHASE for Makefile logic that needs phase-aware guards.
# Source: DI-004-20260422-193652 (TODO/004)
stage0_error_step="run-decomk"
"$decomk_bin" run "${action_args[@]}"

stage0_error_step="clear-failure-artifacts"
clear_stage0_failure_artifacts
