// Command versiongen renders cmd/decomk/version_generated.go from VERSION.
//
// Intent: Keep CLI runtime version output tied to the checked-in VERSION file,
// so source builds and release tags share the same canonical identifier.
// Source: DI-001-20260423-204251 (TODO/001)
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/stevegt/decomk/stage0"
)

var versionPattern = regexp.MustCompile(`^v?[0-9]+\.[0-9]+(?:\.[0-9]+)?$`)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "versiongen:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	fs := flag.NewFlagSet("versiongen", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	repoRoot := fs.String("repo-root", ".", "repository root")
	check := fs.Bool("check", false, "check generated file instead of writing")
	if err := fs.Parse(args); err != nil {
		return err
	}

	absRoot, err := filepath.Abs(*repoRoot)
	if err != nil {
		return fmt.Errorf("abs repo root: %w", err)
	}

	versionPath := filepath.Join(absRoot, "VERSION")
	targetPath := filepath.Join(absRoot, "cmd", "decomk", "version_generated.go")

	versionValue, err := readVersion(versionPath)
	if err != nil {
		return err
	}
	rendered := renderGeneratedVersion(versionValue)

	if *check {
		existing, err := os.ReadFile(targetPath)
		if err != nil {
			return fmt.Errorf("read %s: %w", targetPath, err)
		}
		if !bytes.Equal(existing, rendered) {
			return fmt.Errorf("generated version file is out of date: %s\nrun: go generate ./...", targetPath)
		}
		return nil
	}

	if err := stage0.WriteFileAtomic(targetPath, rendered, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", targetPath, err)
	}
	return nil
}

func readVersion(versionPath string) (string, error) {
	raw, err := os.ReadFile(versionPath)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", versionPath, err)
	}
	value := strings.TrimSpace(string(raw))
	if value == "" {
		return "", fmt.Errorf("VERSION file is empty: %s", versionPath)
	}
	if !versionPattern.MatchString(value) {
		return "", fmt.Errorf("invalid version in %s: %q (expected vMAJOR.MINOR[.PATCH])", versionPath, value)
	}
	if !strings.HasPrefix(value, "v") {
		value = "v" + value
	}
	return value, nil
}

func renderGeneratedVersion(versionValue string) []byte {
	return []byte(fmt.Sprintf(`// Code generated by versiongen. DO NOT EDIT.

package main

const generatedDecomkVersion = %q
`, versionValue))
}
